# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "Card": "00_core.ipynb",
         "Deck": "00_core.ipynb",
         "Hand": "00_core.ipynb",
         "find_defining_class": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hyunjongkimmath.github.io/nbdev_practice/"

git_url = "https://github.com/hyunjongkimmath/nbdev_practice/tree/master/"

def custom_doc_links(name): return None
