# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/example_module.ipynb (unless otherwise specified).

__all__ = ['print_even_numbers', 'Classy']

# Cell
def print_even_numbers(n):
    """
    print even numbers up to ``n``.
    """
    for i in range(0,n,2):
        print(i)

# Cell
class Classy:
    """Class docstring. What will this do?
    """
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def introduce(self):
        print(f'Hi, My name is {self.name}! I am {self.age} years old.')
